### ISSUE TITLE
Server can crash if a player disconnects.

### ISSUE THREAD

**Issue by kdbanman** [polyball/polyball#178]
Trace:

```
/polyball/shared/model/behaviors/GoalBehavior.js:16
        player.score += 1;
              ^

TypeError: Cannot read property 'score' of undefined
    at handleCollision (/polyball/shared/model/behaviors/GoalBehavior.js:16:15)
    at Object.PubSub.emit (/bower_components/PhysicsJS/dist/physicsjs-full.js:2908:17)
    at handleEntityBallCollision (polyball/shared/model/BodyCollider.js:85:41)
    at /cshome/kdbanman/polyball/polyball/shared/model/BodyCollider.js:57:17
    at Function.remove (/node_modules/lodash/lodash.js:6438:13)
    at handleCollision (/cshome/kdbanman/polyball/polyball/shared/model/BodyCollider.js:52:45)
    at Object.PubSub.emit (/bower_components/PhysicsJS/dist/physicsjs-full.js:2908:17)
    at Object.check (/bower_components/PhysicsJS/dist/physicsjs-full.js:7561:29)
    at Object.PubSub.emit (/bower_components/PhysicsJS/dist/physicsjs-full.js:2908:17)
    at Object.sweep /bower_components/PhysicsJS/dist/physicsjs-full.js:9304:29)

Process finished with exit code 1
```

**Comment by kdbanman** [comment]
Easiest to replicate if a round is in session, then just close all the player tabs really fast.

**Comment by kdbanman** [comment]
I've poked this.  The easy solution is to check for null players here in `GoalBehavior.js`:

```javascript
    var handleCollision = function(event){
        var player = config.model.getPlayer(event.ball.lastTouchedID);
        player.score += 1;
    };
```

But I don't know what other assumptions might be be lurking regarding existence of players that may have disconnected.  I'll assign this to @ryant26 for that.

**Comment by ryant26** [comment]
This line was somewhat temporary since I wasn't sure what kind of goal scoring logic we might use. ie. Everyone Else gets a point, you get a point, you loose a point, etc. 


For now I'll simply protect it with a null check
