### ISSUE TITLE
spectator should be removed from the queue on disconnect

### ISSUE THREAD

**Issue by kdbanman** [polyball/polyball#213]

**Comment by kdbanman** [comment]
this is as much a comms issue as it is an engine issue.  we should discuss @ryant26

**Comment by kdbanman** [comment]
manifests as a bug during arena construction if two queued spectators disconnect, then the engine tries to convert them (their ids in the queue) into players:

```

[2016-04-03 02:30:26.092] [INFO] [default] - Initializing game
[2016-04-03 02:30:26.092] [INFO] [default] - Number of Players: 0
[2016-04-03 02:30:26.093] [WARN] [default] - Spectator must have dropped after queueing.  Not converting to player.
[2016-04-03 02:30:26.093] [WARN] [default] - Spectator must have dropped after queueing.  Not converting to player.
[2016-04-03 02:30:26.095] [ERROR] [default] - [TypeError: Cannot read property 'x' of undefined]
TypeError: Cannot read property 'x' of undefined
    at new Arena (c:\Users\kdban\ECE493\polyball\polyball\shared\model\Arena.js:293:35)
    at addOrResetArena (c:\Users\kdban\ECE493\polyball\polyball\shared\Model.js:204:17)
```
